export const FETCH_POLITICIANS_REQUEST = 'FETCH_POLITICIANS_REQUEST';
export const FETCH_POLITICIANS_SUCCESS = 'FETCH_POLITICIANS_SUCCESS';
export const FETCH_POLITICIANS_ERROR = 'FETCH_POLITICIANS_ERROR';
