export const FETCH_POLITICIANS_REQUEST = 'FETCH_POLITICIANS_REQUEST';
export const FETCH_POLITICIANS_SUCCESS = 'FETCH_POLITICIANS_SUCCESS';
export const FETCH_POLITICIANS_SUPPLEMENT_SUCCESS =
  'FETCH_POLITICIANS_SUPPLEMENT_SUCCESS';
export const FETCH_POLITICIANS_ERROR = 'FETCH_POLITICIANS_ERROR';

export const FETCH_STATEMENTS_REQUEST = 'FETCH_STATEMENTS_REQUEST';
export const FETCH_STATEMENTS_SUCCESS = 'FETCH_STATEMENTS_SUCCESS';
export const FETCH_STATEMENTS_SUPPLEMENT_SUCCESS =
  'FETCH_STATEMENTS_SUPPLEMENT_SUCCESS';
export const FETCH_STATEMENTS_ERROR = 'FETCH_STATEMENTS_ERROR';
export const FETCH_STATEMENTS_CLEAR = 'FETCH_STATEMENTS_CLEAR';
